name: endsofinvention
favicon: null
layout_spectrum: 0.6362984504085034
typography_spectrum: 0.5669489286374301
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.33208659244701266
  lightness: 0.6030794007238001
  saturation: 0.7809657093603164
  rhythmicContrast: 0.483502094168216
purpose: []
